export enum GqlStatements {
    CREATE_PROJECT = "CREATE_PROJECT",
    CREATE_SCENE = "CREATE_SCENE",
    UPDATE_SCENE = "UPDATE_SCENE",
    DELETE_PROJECT = "DELETE_PROJECT",
    UPDATE_PROJECT = "UPDATE_PROJECT"
}